# Generated by Django 2.2 on 2022-05-20 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='danhmuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='', max_length=100)),
                ('duongdan', models.CharField(default='', max_length=100)),
                ('mota', models.TextField(default='')),
                ('hoatdong', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='sach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='', max_length=255)),
                ('mota', models.TextField(default='')),
                ('hoatdong', models.BooleanField(default=True)),
                ('danhmuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sach.danhmuc')),
            ],
        ),
    ]
